name: generate animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # allows running the job manually at any time
  workflow_dispatch:

  # run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      GITHUB_USER: ULTRAPAIN

    steps:
      # Set up Git configuration
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Debug Git
      - name: Debug Git Config
        run: git config --list

      # Handle Git Error (Retry 3 times with delay)
      - name: Handle Git Error
        run: |
          for i in {1..3}; do
            git pull origin main && break || sleep 5
          done

      # generates a snake game from a GitHub user (<github_user_name>) contributions graph, output an SVG animation at <svg_out_path>
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ env.GITHUB_USER }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as a GitHub page
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0  # Replace with the specific version you want to use
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Handle the deprecation of Node.js 12
      - name: Update Node.js Version
        uses: actions/setup-node@v2
        with:
          node-version: 16
